### PR TITLE
Cache Path

### PR DESCRIPTION
**Pull request by railken**
Issue: #34 

If the parameter 'cache' is set to true, 'cache_path' is now required.
Maybe the parameter cache should be used already as a path and not as a flag.

### CODE REVIEW

**Comment by KyranRana** [comment]
Can you do me a favour and fix this pull request so it complies with the new changes? I've reverted the commit where i changed the cache conditional. Make sure cache fully works in this pull request.

**Comment by railken** [comment]
I think that if someone wants the cache, the cache_path should be mandatory, otherwise the library doesn't know where to save (and shouldn't guess). 

If you're really into a default cache_path, the cache saved within the library is out of options, so i think the only option remained is by using tmpnam() + sys_get_temp_dir()

A great thing would be also to build a CacheHandlerInterface, so if someone need to save the cache somewhere else or has already a library that manage the cache, he will be able to configure it properly.
The class Storage will implement that interface

**Comment by KyranRana** [comment]
For now I would say that is a bit overkill, and I would rather have the cache_path be set when cache=true. Thanks for the update. Make sure the current tests work as well as the tests for cache_path / cache.

**Comment by railken** [comment]
Done! Check [CacheTest.php](https://github.com/railken/cloudflare-bypass/blob/feature/cache/v2/tests/CacheTest.php)

`OK (6 tests, 26 assertions)`

**Comment by railken** [comment]
Done! Check [CacheTest.php](https://github.com/railken/cloudflare-bypass/blob/feature/cache/v2/tests/CacheTest.php)

`OK (7 tests, 27 assertions)`

**Comment by KyranRana** [comment]
Rather than doing a iteration and deleting each file from the caching dir, why not remove the file which has been created for that request? 

Look in CurlTest.php at `$cache_file`. The cache file generated for each site is `md5(hostname)`.

**Comment by railken** [comment]
As you wish, more commits for me!

**Comment by KyranRana** [comment]
Just added a few commits of my own. They shouldn't affect your tests, most of them are cosmetic / consistency-related. I moved over that removal check to CurlTest and GuzzleHttpTest (`file_exists($file) && unlink($file)`). That is a good check as it prevents the possibility of a cached clearance token fluke-ing the tests. 👍

**Comment by railken** [comment]
Good, waiting for the merge 👍

**Pull request merged**
